import { Inter } from "next/font/google";
import "./globals.css";
import { SchoolProvider } from "@/context/SchoolProvider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "School System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className} style={{ display: "flex" }}>
        <SchoolProvider>
          <header className="w-1/5">
            <Navbar />
          </header>

          <main className="w-4/5">{children}</main>
        </SchoolProvider>
      </body>
    </html>
  );
}
