import { Inter } from "next/font/google";
import "./globals.css";
import { SchoolProvider } from "@/context/SchoolProvider";
import Navbar from "./components/Navbar";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "School System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className} style={{ display: "flex" }}>
        <SchoolProvider>
          <Suspense fallback={Loading}>
            <header className="w-1/5">
              <Navbar />
            </header>

            <main className="w-4/5">{children}</main>
          </Suspense>
        </SchoolProvider>
      </body>
    </html>
  );
}
